server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /api/who/ {
    proxy_pass https://ghoapi.azureedge.net/;
    proxy_set_header Host ghoapi.azureedge.net;
    proxy_ssl_server_name on;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
